spring:
    application:
        name: TestApp
    data:
        mongodb:
            uri: "mongodb://127.0.0.1:27017/users"
            database: "users"

    #   R2DBC
    r2dbc:
        url: r2dbc:mysql://localhost:3306/friendmanagement
        username: root
        password: Now123DQN
    #   JPA
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
#    Datasource
    datasource:
      url: jdbc:mysql://localhost:3306/friendmanagement
      username: root
      password: Now123DQN
      driver-class-name: com.mysql.cj.jdbc.Driver

